### PR TITLE
Corrected installation process

### PR DESCRIPTION
**Pull request by SilverC0de**

### CODE REVIEW

**Comment by SilverC0de** [comment]
The installation process is not correct so I fixed it

**Comment by xRaptoorZz** [comment]
is this a scam??? The bot works great, very great, if it wasnt for some transfer not authorized from me :D
All the money won was transfered to a new address from mine, how strange!! Use those 30 bucks to buy some dignity

**Comment by SilverC0de** [comment]
My bad, it's not a scam tho, buh yeah, I'll backoff

**Comment by SilverC0de** [comment]
WAIT, What do you mean your $30 was transferred out, this wasn't me which means something fishy is going on, I am not trying to scam, I just want to improve the codebase because I am a developer as well

**Comment by SilverC0de** [comment]
SCAMMMMM!!!!!

**Pull request closed without merging**
